<?php

/**
 * Add custom cities to WooCommerce
 * 
 * This code snippet adds custom cities to WooCommerce using the WC City Select plugin.
 * 
 * Steps to add cities:
 * 1. Install and activate the WC City Select plugin (https://wordpress.org/plugins/wc-city)
 * 2. Add the list of cities to the functions.php file or with the Code Snippets plugin (https://es.wordpress.org/plugins/code-snippets/).
 * 3. Use the wc_city_select_cities filter to load your cities.
 * 
 */

add_filter("wc_city_select_cities", "my_cities");

function my_cities($cities)
{
    $cities["PE"] = [
        "AMA" => [
            "Bagua / Bagua",
            "Bagua / Aramango",
            "Bagua / Copallin",
            "Bagua / El Parco",
            "Bagua / Imaza",
            "Bagua / La Peca",
            "Bongara / Jumbilla",
            "Bongara / Chisquilla",
            "Bongara / Churuja",
            "Bongara / Corosha",
            "Bongara / Cuispes",
            "Bongara / Florida",
            "Bongara / Jazan",
            "Bongara / Recta",
            "Bongara / San Carlos",
            "Bongara / Shipasbamba",
            "Bongara / Valera",
            "Bongara / Yambrasbamba",
            "Chachapoyas / Chachapoyas",
            "Chachapoyas / Asuncion",
            "Chachapoyas / Balsas",
            "Chachapoyas / Cheto",
            "Chachapoyas / Chiliquin",
            "Chachapoyas / Chuquibamba",
            "Chachapoyas / Granada",
            "Chachapoyas / Huancas",
            "Chachapoyas / La Jalca",
            "Chachapoyas / Leimebamba",
            "Chachapoyas / Levanto",
            "Chachapoyas / Magdalena",
            "Chachapoyas / Mariscal Castilla",
            "Chachapoyas / Molinopampa",
            "Chachapoyas / Montevideo",
            "Chachapoyas / Olleros",
            "Chachapoyas / Quinjalca",
            "Chachapoyas / San Francisco De Daguas",
            "Chachapoyas / San Isidro De Maino",
            "Chachapoyas / Soloco",
            "Chachapoyas / Sonche",
            "Condorcanqui / Nieva",
            "Condorcanqui / El Cenepa",
            "Condorcanqui / Rio Santiago",
            "Luya / Lamud",
            "Luya / Camporredondo",
            "Luya / Cocabamba",
            "Luya / Colcamar",
            "Luya / Conila",
            "Luya / Inguilpata",
            "Luya / Longuita",
            "Luya / Lonya Chico",
            "Luya / Luya",
            "Luya / Luya Viejo",
            "Luya / Maria",
            "Luya / Ocalli",
            "Luya / Ocumal",
            "Luya / Pisuquia",
            "Luya / Providencia",
            "Luya / San Cristobal",
            "Luya / San Francisco Del Yeso",
            "Luya / San Jeronimo",
            "Luya / San Juan De Lopecancha",
            "Luya / Santa Catalina",
            "Luya / Santo Tomas",
            "Luya / Tingo",
            "Luya / Trita",
            "Rodriguez De Mendoza / San Nicolas",
            "Rodriguez De Mendoza / Chirimoto",
            "Rodriguez De Mendoza / Cochamal",
            "Rodriguez De Mendoza / Huambo",
            "Rodriguez De Mendoza / Limabamba",
            "Rodriguez De Mendoza / Longar",
            "Rodriguez De Mendoza / Mariscal Benavides",
            "Rodriguez De Mendoza / Milpuc",
            "Rodriguez De Mendoza / Omia",
            "Rodriguez De Mendoza / Santa Rosa",
            "Rodriguez De Mendoza / Totora",
            "Rodriguez De Mendoza / Vista Alegre",
            "Utcubamba / Bagua Grande",
            "Utcubamba / Cajaruro",
            "Utcubamba / Cumba",
            "Utcubamba / El Milagro",
            "Utcubamba / Jamalca",
            "Utcubamba / Lonya Grande",
            "Utcubamba / Yamon",
        ],

        "ANC" => [
            "Aija / Aija",
            "Aija / Coris",
            "Aija / Huacllan",
            "Aija / La Merced",
            "Aija / Succha",
            "Antonio Raymondi / Llamellin",
            "Antonio Raymondi / Aczo",
            "Antonio Raymondi / Chaccho",
            "Antonio Raymondi / Chingas",
            "Antonio Raymondi / Mirgas",
            "Antonio Raymondi / San Juan De Rontoy",
            "Asuncion / Chacas",
            "Asuncion / Acochaca",
            "Bolognesi / Chiquian",
            "Bolognesi / Abelardo Pardo Lezameta",
            "Bolognesi / Antonio Raymondi",
            "Bolognesi / Aquia",
            "Bolognesi / Cajacay",
            "Bolognesi / Canis",
            "Bolognesi / Colquioc",
            "Bolognesi / Huallanca",
            "Bolognesi / Huasta",
            "Bolognesi / Huayllacayan",
            "Bolognesi / La Primavera",
            "Bolognesi / Mangas",
            "Bolognesi / Pacllon",
            "Bolognesi / San Miguel De Corpanqui",
            "Bolognesi / Ticllos",
            "Carhuaz / Carhuaz",
            "Carhuaz / Acopampa",
            "Carhuaz / Amashca",
            "Carhuaz / Anta",
            "Carhuaz / Ataquero",
            "Carhuaz / Marcara",
            "Carhuaz / Pariahuanca",
            "Carhuaz / San Miguel De Aco",
            "Carhuaz / Shilla",
            "Carhuaz / Tinco",
            "Carhuaz / Yungar",
            "Carlos Fermin Fitzcarrald / San Luis",
            "Carlos Fermin Fitzcarrald / San Nicolas",
            "Carlos Fermin Fitzcarrald / Yauya",
            "Casma / Casma",
            "Casma / Buena Vista Alta",
            "Casma / Comandante Noel",
            "Casma / Yautan",
            "Corongo / Corongo",
            "Corongo / Aco",
            "Corongo / Bambas",
            "Corongo / Cusca",
            "Corongo / La Pampa",
            "Corongo / Yanac",
            "Corongo / Yupan",
            "Huaraz / Huaraz",
            "Huaraz / Cochabamba",
            "Huaraz / Colcabamba",
            "Huaraz / Huanchay",
            "Huaraz / Independencia",
            "Huaraz / Jangas",
            "Huaraz / La Libertad",
            "Huaraz / Olleros",
            "Huaraz / Pampas",
            "Huaraz / Pariacoto",
            "Huaraz / Pira",
            "Huaraz / Tarica",
            "Huari / Huari",
            "Huari / Anra",
            "Huari / Cajay",
            "Huari / Chavin De Huantar",
            "Huari / Huacachi",
            "Huari / Huacchis",
            "Huari / Huachis",
            "Huari / Huantar",
            "Huari / Masin",
            "Huari / Paucas",
            "Huari / Ponto",
            "Huari / Rahuapampa",
            "Huari / Rapayan",
            "Huari / San Marcos",
            "Huari / San Pedro De Chana",
            "Huari / Uco",
            "Huarmey / Huarmey",
            "Huarmey / Cochapeti",
            "Huarmey / Culebras",
            "Huarmey / Huayan",
            "Huarmey / Malvas",
            "Huaylas / Caraz",
            "Huaylas / Huallanca",
            "Huaylas / Huata",
            "Huaylas / Huaylas",
            "Huaylas / Mato",
            "Huaylas / Pamparomas",
            "Huaylas / Pueblo Libre",
            "Huaylas / Santa Cruz",
            "Huaylas / Santo Toribio",
            "Huaylas / Yuracmarca",
            "Mariscal Luzuriaga / Piscobamba",
            "Mariscal Luzuriaga / Casca",
            "Mariscal Luzuriaga / Eleazar Guzman Barron",
            "Mariscal Luzuriaga / Fidel Olivas Escudero",
            "Mariscal Luzuriaga / Llama",
            "Mariscal Luzuriaga / Llumpa",
            "Mariscal Luzuriaga / Lucma",
            "Mariscal Luzuriaga / Musga",
            "Ocros / Ocros",
            "Ocros / Acas",
            "Ocros / Cajamarquilla",
            "Ocros / Carhuapampa",
            "Ocros / Cochas",
            "Ocros / Congas",
            "Ocros / Llipa",
            "Ocros / San Cristobal De Rajan",
            "Ocros / San Pedro",
            "Ocros / Santiago De Chilcas",
            "Pallasca / Cabana",
            "Pallasca / Bolognesi",
            "Pallasca / Conchucos",
            "Pallasca / Huacaschuque",
            "Pallasca / Huandoval",
            "Pallasca / Lacabamba",
            "Pallasca / Llapo",
            "Pallasca / Pallasca",
            "Pallasca / Pampas",
            "Pallasca / Santa Rosa",
            "Pallasca / Tauca",
            "Pomabamba / Pomabamba",
            "Pomabamba / Huayllan",
            "Pomabamba / Parobamba",
            "Pomabamba / Quinuabamba",
            "Recuay / Recuay",
            "Recuay / Catac",
            "Recuay / Cotaparaco",
            "Recuay / Huayllapampa",
            "Recuay / Llacllin",
            "Recuay / Marca",
            "Recuay / Pampas Chico",
            "Recuay / Pararin",
            "Recuay / Tapacocha",
            "Recuay / Ticapampa",
            "Santa / Chimbote",
            "Santa / Caceres Del Peru",
            "Santa / Coishco",
            "Santa / Macate",
            "Santa / Moro",
            "Santa / Nepeña",
            "Santa / Samanco",
            "Santa / Santa",
            "Santa / Nuevo Chimbote",
            "Sihuas / Sihuas",
            "Sihuas / Acobamba",
            "Sihuas / Alfonso Ugarte",
            "Sihuas / Cashapampa",
            "Sihuas / Chingalpo",
            "Sihuas / Huayllabamba",
            "Sihuas / Quiches",
            "Sihuas / Ragash",
            "Sihuas / San Juan",
            "Sihuas / Sicsibamba",
            "Yungay / Yungay",
            "Yungay / Cascapara",
            "Yungay / Mancos",
            "Yungay / Matacoto",
            "Yungay / Quillo",
            "Yungay / Ranrahirca",
            "Yungay / Shupluy",
            "Yungay / Yanama",
        ],
        "APU" => [
            "Abancay / Abancay",
            "Abancay / Chacoche",
            "Abancay / Circa",
            "Abancay / Curahuasi",
            "Abancay / Huanipaca",
            "Abancay / Lambrama",
            "Abancay / Pichirhua",
            "Abancay / San Pedro De Cachora",
            "Abancay / Tamburco",
            "Andahuaylas / Andahuaylas",
            "Andahuaylas / Andarapa",
            "Andahuaylas / Chiara",
            "Andahuaylas / Huancarama",
            "Andahuaylas / Huancaray",
            "Andahuaylas / Huayana",
            "Andahuaylas / Kishuara",
            "Andahuaylas / Pacobamba",
            "Andahuaylas / Pacucha",
            "Andahuaylas / Pampachiri",
            "Andahuaylas / Pomacocha",
            "Andahuaylas / San Antonio De Cachi",
            "Andahuaylas / San Jeronimo",
            "Andahuaylas / San Miguel De Chaccrampa",
            "Andahuaylas / Santa Maria De Chicmo",
            "Andahuaylas / Talavera",
            "Andahuaylas / Tumay Huaraca",
            "Andahuaylas / Turpo",
            "Andahuaylas / Kaquiabamba",
            "Andahuaylas / Jose Maria Arguedas",
            "Antabamba / Antabamba",
            "Antabamba / El Oro",
            "Antabamba / Huaquirca",
            "Antabamba / Juan Espinoza Medrano",
            "Antabamba / Oropesa",
            "Antabamba / Pachaconas",
            "Antabamba / Sabaino",
            "Aymaraes / Chalhuanca",
            "Aymaraes / Capaya",
            "Aymaraes / Caraybamba",
            "Aymaraes / Chapimarca",
            "Aymaraes / Colcabamba",
            "Aymaraes / Cotaruse",
            "Aymaraes / Huayllo",
            "Aymaraes / Justo Apu Sahuaraura",
            "Aymaraes / Lucre",
            "Aymaraes / Pocohuanca",
            "Aymaraes / San Juan De Chacña",
            "Aymaraes / Sañayca",
            "Aymaraes / Soraya",
            "Aymaraes / Tapairihua",
            "Aymaraes / Tintay",
            "Aymaraes / Toraya",
            "Aymaraes / Yanaca",
            "Chincheros / Chincheros",
            "Chincheros / Anco-Huallo",
            "Chincheros / Cocharcas",
            "Chincheros / Huaccana",
            "Chincheros / Ocobamba",
            "Chincheros / Ongoy",
            "Chincheros / Uranmarca",
            "Chincheros / Ranracancha",
            "Chincheros / Rocchacc",
            "Chincheros / El Porvenir",
            "Chincheros / Los Chankas",
            "Chincheros / Ahuayro",
            "Cotabambas / Tambobamba",
            "Cotabambas / Cotabambas",
            "Cotabambas / Coyllurqui",
            "Cotabambas / Haquira",
            "Cotabambas / Mara",
            "Cotabambas / Challhuahuacho",
            "Grau / Chuquibambilla",
            "Grau / Curpahuasi",
            "Grau / Gamarra",
            "Grau / Huayllati",
            "Grau / Mamara",
            "Grau / Micaela Bastidas",
            "Grau / Pataypampa",
            "Grau / Progreso",
            "Grau / San Antonio",
            "Grau / Santa Rosa",
            "Grau / Turpay",
            "Grau / Vilcabamba",
            "Grau / Virundo",
            "Grau / Curasco",
        ],
        "ARE" => [
            "Arequipa / Arequipa",
            "Arequipa / Alto Selva Alegre",
            "Arequipa / Cayma",
            "Arequipa / Cerro Colorado",
            "Arequipa / Characato",
            "Arequipa / Chiguata",
            "Arequipa / Jacobo Hunter",
            "Arequipa / La Joya",
            "Arequipa / Mariano Melgar",
            "Arequipa / Miraflores",
            "Arequipa / Mollebaya",
            "Arequipa / Paucarpata",
            "Arequipa / Pocsi",
            "Arequipa / Polobaya",
            "Arequipa / Quequeña",
            "Arequipa / Sabandia",
            "Arequipa / Sachaca",
            "Arequipa / San Juan De Siguas",
            "Arequipa / San Juan De Tarucani",
            "Arequipa / Santa Isabel De Siguas",
            "Arequipa / Santa Rita De Siguas",
            "Arequipa / Socabaya",
            "Arequipa / Tiabaya",
            "Arequipa / Uchumayo",
            "Arequipa / Vitor",
            "Arequipa / Yanahuara",
            "Arequipa / Yarabamba",
            "Arequipa / Yura",
            "Arequipa / Jose Luis Bustamante Y Rivero",
            "Camana / Camana",
            "Camana / Jose Maria Quimper",
            "Camana / Mariano Nicolas Valcarcel",
            "Camana / Mariscal Caceres",
            "Camana / Nicolas De Pierola",
            "Camana / Ocoña",
            "Camana / Quilca",
            "Camana / Samuel Pastor",
            "Caraveli / Caraveli",
            "Caraveli / Acari",
            "Caraveli / Atico",
            "Caraveli / Atiquipa",
            "Caraveli / Bella Union",
            "Caraveli / Cahuacho",
            "Caraveli / Chala",
            "Caraveli / Chaparra",
            "Caraveli / Huanuhuanu",
            "Caraveli / Jaqui",
            "Caraveli / Lomas",
            "Caraveli / Quicacha",
            "Caraveli / Yauca",
            "Castilla / Aplao",
            "Castilla / Andagua",
            "Castilla / Ayo",
            "Castilla / Chachas",
            "Castilla / Chilcaymarca",
            "Castilla / Choco",
            "Castilla / Huancarqui",
            "Castilla / Machaguay",
            "Castilla / Orcopampa",
            "Castilla / Pampacolca",
            "Castilla / Tipan",
            "Castilla / Uñon",
            "Castilla / Uraca",
            "Castilla / Viraco",
            "Caylloma / Chivay",
            "Caylloma / Achoma",
            "Caylloma / Cabanaconde",
            "Caylloma / Callalli",
            "Caylloma / Caylloma",
            "Caylloma / Coporaque",
            "Caylloma / Huambo",
            "Caylloma / Huanca",
            "Caylloma / Ichupampa",
            "Caylloma / Lari",
            "Caylloma / Lluta",
            "Caylloma / Maca",
            "Caylloma / Madrigal",
            "Caylloma / San Antonio De Chuca",
            "Caylloma / Sibayo",
            "Caylloma / Tapay",
            "Caylloma / Tisco",
            "Caylloma / Tuti",
            "Caylloma / Yanque",
            "Caylloma / Majes",
            "Condesuyos / Chuquibamba",
            "Condesuyos / Andaray",
            "Condesuyos / Cayarani",
            "Condesuyos / Chichas",
            "Condesuyos / Iray",
            "Condesuyos / Rio Grande",
            "Condesuyos / Salamanca",
            "Condesuyos / Yanaquihua",
            "Islay / Mollendo",
            "Islay / Cocachacra",
            "Islay / Dean Valdivia",
            "Islay / Islay",
            "Islay / Mejia",
            "Islay / Punta De Bombon",
            "La Union / Cotahuasi",
            "La Union / Alca",
            "La Union / Charcana",
            "La Union / Huaynacotas",
            "La Union / Pampamarca",
            "La Union / Puyca",
            "La Union / Quechualla",
            "La Union / Sayla",
            "La Union / Tauria",
            "La Union / Tomepampa",
            "La Union / Toro",
        ],

        "AYA" => [
            "Cangallo / Cangallo",
            "Cangallo / Chuschi",
            "Cangallo / Los Morochucos",
            "Cangallo / Maria Parado De Bellido",
            "Cangallo / Paras",
            "Cangallo / Totos",
            "Huamanga / Ayacucho",
            "Huamanga / Acocro",
            "Huamanga / Acos Vinchos",
            "Huamanga / Carmen Alto",
            "Huamanga / Chiara",
            "Huamanga / Ocros",
            "Huamanga / Pacaycasa",
            "Huamanga / Quinua",
            "Huamanga / San Jose De Ticllas",
            "Huamanga / San Juan Bautista",
            "Huamanga / Santiago De Pischa",
            "Huamanga / Socos",
            "Huamanga / Tambillo",
            "Huamanga / Vinchos",
            "Huamanga / Jesus Nazareno",
            "Huamanga / Andres Avelino Caceres Dorregaray",
            "Huanca Sancos / Sancos",
            "Huanca Sancos / Carapo",
            "Huanca Sancos / Sacsamarca",
            "Huanca Sancos / Santiago De Lucanamarca",
            "Huanta / Huanta",
            "Huanta / Ayahuanco",
            "Huanta / Huamanguilla",
            "Huanta / Iguain",
            "Huanta / Luricocha",
            "Huanta / Santillana",
            "Huanta / Sivia",
            "Huanta / Llochegua",
            "Huanta / Canayre",
            "Huanta / Uchuraccay",
            "Huanta / Pucacolpa",
            "Huanta / Chaca",
            "Huanta / Putis",
            "La Mar / San Miguel",
            "La Mar / Anco",
            "La Mar / Ayna",
            "La Mar / Chilcas",
            "La Mar / Chungui",
            "La Mar / Luis Carranza",
            "La Mar / Santa Rosa",
            "La Mar / Tambo",
            "La Mar / Samugari",
            "La Mar / Anchihuay",
            "La Mar / Oronccoy",
            "La Mar / Union Progreso",
            "La Mar / Rio Magdalena",
            "La Mar / Ninabamba",
            "La Mar / Patibamba",
            "Lucanas / Puquio",
            "Lucanas / Aucara",
            "Lucanas / Cabana",
            "Lucanas / Carmen Salcedo",
            "Lucanas / Chaviña",
            "Lucanas / Chipao",
            "Lucanas / Huac-Huas",
            "Lucanas / Laramate",
            "Lucanas / Leoncio Prado",
            "Lucanas / Llauta",
            "Lucanas / Lucanas",
            "Lucanas / Ocaña",
            "Lucanas / Otoca",
            "Lucanas / Saisa",
            "Lucanas / San Cristobal",
            "Lucanas / San Juan",
            "Lucanas / San Pedro",
            "Lucanas / San Pedro De Palco",
            "Lucanas / Sancos",
            "Lucanas / Santa Ana De Huaycahuacho",
            "Lucanas / Santa Lucia",
            "Parinacochas / Coracora",
            "Parinacochas / Chumpi",
            "Parinacochas / Coronel Castañeda",
            "Parinacochas / Pacapausa",
            "Parinacochas / Pullo",
            "Parinacochas / Puyusca",
            "Parinacochas / San Francisco De Ravacayco",
            "Parinacochas / Upahuacho",
            "Paucar Del Sara Sara / Pausa",
            "Paucar Del Sara Sara / Colta",
            "Paucar Del Sara Sara / Corculla",
            "Paucar Del Sara Sara / Lampa",
            "Paucar Del Sara Sara / Marcabamba",
            "Paucar Del Sara Sara / Oyolo",
            "Paucar Del Sara Sara / Pararca",
            "Paucar Del Sara Sara / San Javier De Alpabamba",
            "Paucar Del Sara Sara / San Jose De Ushua",
            "Paucar Del Sara Sara / Sara Sara",
            "Sucre / Querobamba",
            "Sucre / Belen",
            "Sucre / Chalcos",
            "Sucre / Chilcayoc",
            "Sucre / Huacaña",
            "Sucre / Morcolla",
            "Sucre / Paico",
            "Sucre / San Pedro De Larcay",
            "Sucre / San Salvador De Quije",
            "Sucre / Santiago De Paucaray",
            "Sucre / Soras",
            "Victor Fajardo / Huancapi",
            "Victor Fajardo / Alcamenca",
            "Victor Fajardo / Apongo",
            "Victor Fajardo / Asquipata",
            "Victor Fajardo / Canaria",
            "Victor Fajardo / Cayara",
            "Victor Fajardo / Colca",
            "Victor Fajardo / Huamanquiquia",
            "Victor Fajardo / Huancaraylla",
            "Victor Fajardo / Huaya",
            "Victor Fajardo / Sarhua",
            "Victor Fajardo / Vilcanchos",
            "Vilcas Huaman / Vilcas Huaman",
            "Vilcas Huaman / Accomarca",
            "Vilcas Huaman / Carhuanca",
            "Vilcas Huaman / Concepcion",
            "Vilcas Huaman / Huambalpa",
            "Vilcas Huaman / Independencia",
            "Vilcas Huaman / Saurama",
            "Vilcas Huaman / Vischongo",
        ],

        "CAJ" => [
            "Cajabamba / Cajabamba",
            "Cajabamba / Cachachi",
            "Cajabamba / Condebamba",
            "Cajabamba / Sitacocha",
            "Cajamarca / Cajamarca",
            "Cajamarca / Asuncion",
            "Cajamarca / Chetilla",
            "Cajamarca / Cospan",
            "Cajamarca / Encañada",
            "Cajamarca / Jesus",
            "Cajamarca / Llacanora",
            "Cajamarca / Los Baños Del Inca",
            "Cajamarca / Magdalena",
            "Cajamarca / Matara",
            "Cajamarca / Namora",
            "Cajamarca / San Juan",
            "Celendin / Celendin",
            "Celendin / Chumuch",
            "Celendin / Cortegana",
            "Celendin / Huasmin",
            "Celendin / Jorge Chavez",
            "Celendin / Jose Galvez",
            "Celendin / Miguel Iglesias",
            "Celendin / Oxamarca",
            "Celendin / Sorochuco",
            "Celendin / Sucre",
            "Celendin / Utco",
            "Celendin / La Libertad De Pallan",
            "Chota / Chota",
            "Chota / Anguia",
            "Chota / Chadin",
            "Chota / Chiguirip",
            "Chota / Chimban",
            "Chota / Choropampa",
            "Chota / Cochabamba",
            "Chota / Conchan",
            "Chota / Huambos",
            "Chota / Lajas",
            "Chota / Llama",
            "Chota / Miracosta",
            "Chota / Paccha",
            "Chota / Pion",
            "Chota / Querocoto",
            "Chota / San Juan De Licupis",
            "Chota / Tacabamba",
            "Chota / Tocmoche",
            "Chota / Chalamarca",
            "Contumaza / Contumaza",
            "Contumaza / Chilete",
            "Contumaza / Cupisnique",
            "Contumaza / Guzmango",
            "Contumaza / San Benito",
            "Contumaza / Santa Cruz De Toledo",
            "Contumaza / Tantarica",
            "Contumaza / Yonan",
            "Cutervo / Cutervo",
            "Cutervo / Callayuc",
            "Cutervo / Choros",
            "Cutervo / Cujillo",
            "Cutervo / La Ramada",
            "Cutervo / Pimpingos",
            "Cutervo / Querocotillo",
            "Cutervo / San Andres De Cutervo",
            "Cutervo / San Juan De Cutervo",
            "Cutervo / San Luis De Lucma",
            "Cutervo / Santa Cruz",
            "Cutervo / Santo Domingo De La Capilla",
            "Cutervo / Santo Tomas",
            "Cutervo / Socota",
            "Cutervo / Toribio Casanova",
            "Hualgayoc / Bambamarca",
            "Hualgayoc / Chugur",
            "Hualgayoc / Hualgayoc",
            "Jaen / Jaen",
            "Jaen / Bellavista",
            "Jaen / Chontali",
            "Jaen / Colasay",
            "Jaen / Huabal",
            "Jaen / Las Pirias",
            "Jaen / Pomahuaca",
            "Jaen / Pucara",
            "Jaen / Sallique",
            "Jaen / San Felipe",
            "Jaen / San Jose Del Alto",
            "Jaen / Santa Rosa",
            "San Ignacio / San Ignacio",
            "San Ignacio / Chirinos",
            "San Ignacio / Huarango",
            "San Ignacio / La Coipa",
            "San Ignacio / Namballe",
            "San Ignacio / San Jose De Lourdes",
            "San Ignacio / Tabaconas",
            "San Marcos / Pedro Galvez",
            "San Marcos / Chancay",
            "San Marcos / Eduardo Villanueva",
            "San Marcos / Gregorio Pita",
            "San Marcos / Ichocan",
            "San Marcos / Jose Manuel Quiroz",
            "San Marcos / Jose Sabogal",
            "San Miguel / San Miguel",
            "San Miguel / Bolivar",
            "San Miguel / Calquis",
            "San Miguel / Catilluc",
            "San Miguel / El Prado",
            "San Miguel / La Florida",
            "San Miguel / Llapa",
            "San Miguel / Nanchoc",
            "San Miguel / Niepos",
            "San Miguel / San Gregorio",
            "San Miguel / San Silvestre De Cochan",
            "San Miguel / Tongod",
            "San Miguel / Union Agua Blanca",
            "San Pablo / San Pablo",
            "San Pablo / San Bernardino",
            "San Pablo / San Luis",
            "San Pablo / Tumbaden",
            "Santa Cruz / Santa Cruz",
            "Santa Cruz / Andabamba",
            "Santa Cruz / Catache",
            "Santa Cruz / Chancaybaños",
            "Santa Cruz / La Esperanza",
            "Santa Cruz / Ninabamba",
            "Santa Cruz / Pulan",
            "Santa Cruz / Saucepampa",
            "Santa Cruz / Sexi",
            "Santa Cruz / Uticyacu",
            "Santa Cruz / Yauyucan",
        ],

        "CAL" => [
            "Callao",
            "Bellavista",
            "Carmen de La Legua Reynoso",
            "La Perla",
            "La Punta",
            "Ventanilla",
            "Mi Peru",
        ],

        "CUS" => [
            "Acomayo / Acomayo",
            "Acomayo / Acopia",
            "Acomayo / Acos",
            "Acomayo / Mosoc Llacta",
            "Acomayo / Pomacanchi",
            "Acomayo / Rondocan",
            "Acomayo / Sangarara",
            "Anta / Anta",
            "Anta / Ancahuasi",
            "Anta / Cachimayo",
            "Anta / Chinchaypujio",
            "Anta / Huarocondo",
            "Anta / Limatambo",
            "Anta / Mollepata",
            "Anta / Pucyura",
            "Anta / Zurite",
            "Calca / Calca",
            "Calca / Coya",
            "Calca / Lamay",
            "Calca / Lares",
            "Calca / Pisac",
            "Calca / San Salvador",
            "Calca / Taray",
            "Calca / Yanatile",
            "Canas / Yanaoca",
            "Canas / Checca",
            "Canas / Kunturkanki",
            "Canas / Langui",
            "Canas / Layo",
            "Canas / Pampamarca",
            "Canas / Quehue",
            "Canas / Tupac Amaru",
            "Canchis / Sicuani",
            "Canchis / Checacupe",
            "Canchis / Combapata",
            "Canchis / Marangani",
            "Canchis / Pitumarca",
            "Canchis / San Pablo",
            "Canchis / San Pedro",
            "Canchis / Tinta",
            "Chumbivilcas / Santo Tomas",
            "Chumbivilcas / Capacmarca",
            "Chumbivilcas / Chamaca",
            "Chumbivilcas / Colquemarca",
            "Chumbivilcas / Livitaca",
            "Chumbivilcas / Llusco",
            "Chumbivilcas / Quiñota",
            "Chumbivilcas / Velille",
            "Cusco / Cusco",
            "Cusco / Ccorca",
            "Cusco / Poroy",
            "Cusco / San Jeronimo",
            "Cusco / San Sebastian",
            "Cusco / Santiago",
            "Cusco / Saylla",
            "Cusco / Wanchaq",
            "Espinar / Espinar",
            "Espinar / Condoroma",
            "Espinar / Coporaque",
            "Espinar / Ocoruro",
            "Espinar / Pallpata",
            "Espinar / Pichigua",
            "Espinar / Suyckutambo",
            "Espinar / Alto Pichigua",
            "La Convencion / Santa Ana",
            "La Convencion / Echarate",
            "La Convencion / Huayopata",
            "La Convencion / Maranura",
            "La Convencion / Ocobamba",
            "La Convencion / Quellouno",
            "La Convencion / Quimbiri",
            "La Convencion / Santa Teresa",
            "La Convencion / Vilcabamba",
            "La Convencion / Pichari",
            "La Convencion / Inkawasi",
            "La Convencion / Villa Virgen",
            "La Convencion / Villa Kintiarina",
            "La Convencion / Megantoni",
            "La Convencion / Kumpirushiato",
            "La Convencion / Cielo Punco",
            "La Convencion / Manitea",
            "La Convencion / Union Asháninka",
            "Paruro / Paruro",
            "Paruro / Accha",
            "Paruro / Ccapi",
            "Paruro / Colcha",
            "Paruro / Huanoquite",
            "Paruro / Omacha",
            "Paruro / Paccaritambo",
            "Paruro / Pillpinto",
            "Paruro / Yaurisque",
            "Paucartambo / Paucartambo",
            "Paucartambo / Caicay",
            "Paucartambo / Challabamba",
            "Paucartambo / Colquepata",
            "Paucartambo / Huancarani",
            "Paucartambo / Kosñipata",
            "Quispicanchi / Urcos",
            "Quispicanchi / Andahuaylillas",
            "Quispicanchi / Camanti",
            "Quispicanchi / Ccarhuayo",
            "Quispicanchi / Ccatca",
            "Quispicanchi / Cusipata",
            "Quispicanchi / Huaro",
            "Quispicanchi / Lucre",
            "Quispicanchi / Marcapata",
            "Quispicanchi / Ocongate",
            "Quispicanchi / Oropesa",
            "Quispicanchi / Quiquijana",
            "Urubamba / Urubamba",
            "Urubamba / Chinchero",
            "Urubamba / Huayllabamba",
            "Urubamba / Machupicchu",
            "Urubamba / Maras",
            "Urubamba / Ollantaytambo",
            "Urubamba / Yucay",
        ],

        "HUC" => [
            "Ambo / Ambo",
            "Ambo / Cayna",
            "Ambo / Colpas",
            "Ambo / Conchamarca",
            "Ambo / Huacar",
            "Ambo / San Francisco",
            "Ambo / San Rafael",
            "Ambo / Tomay Kichwa",
            "Dos De Mayo / La Union",
            "Dos De Mayo / Chuquis",
            "Dos De Mayo / Marias",
            "Dos De Mayo / Pachas",
            "Dos De Mayo / Quivilla",
            "Dos De Mayo / Ripan",
            "Dos De Mayo / Shunqui",
            "Dos De Mayo / Sillapata",
            "Dos De Mayo / Yanas",
            "Huacaybamba / Huacaybamba",
            "Huacaybamba / Canchabamba",
            "Huacaybamba / Cochabamba",
            "Huacaybamba / Pinra",
            "Huamalies / Llata",
            "Huamalies / Arancay",
            "Huamalies / Chavin De Pariarca",
            "Huamalies / Jacas Grande",
            "Huamalies / Jircan",
            "Huamalies / Miraflores",
            "Huamalies / Monzon",
            "Huamalies / Punchao",
            "Huamalies / Puños",
            "Huamalies / Singa",
            "Huamalies / Tantamayo",
            "Huanuco / Huanuco",
            "Huanuco / Amarilis",
            "Huanuco / Chinchao",
            "Huanuco / Churubamba",
            "Huanuco / Margos",
            "Huanuco / Quisqui",
            "Huanuco / San Francisco De Cayran",
            "Huanuco / San Pedro De Chaulan",
            "Huanuco / Santa Maria Del Valle",
            "Huanuco / Yarumayo",
            "Huanuco / Pillco Marca",
            "Huanuco / Yacus",
            "Huanuco / San Pablo De Pillao",
            "Lauricocha / Jesus",
            "Lauricocha / Baños",
            "Lauricocha / Jivia",
            "Lauricocha / Queropalca",
            "Lauricocha / Rondos",
            "Lauricocha / San Francisco De Asis",
            "Lauricocha / San Miguel De Cauri",
            "Leoncio Prado / Rupa-Rupa",
            "Leoncio Prado / Daniel Alomias Robles",
            "Leoncio Prado / Hermilio Valdizan",
            "Leoncio Prado / Jose Crespo Y Castillo",
            "Leoncio Prado / Luyando",
            "Leoncio Prado / Mariano Damaso Beraun",
            "Leoncio Prado / Pucayacu",
            "Leoncio Prado / Castillo Grande",
            "Leoncio Prado / Pueblo Nuevo",
            "Leoncio Prado / Santo Domingo De Anda",
            "Marañon / Huacrachuco",
            "Marañon / Cholon",
            "Marañon / San Buenaventura",
            "Marañon / La Morada",
            "Marañon / Santa Rosa De Alto Yanajanca",
            "Pachitea / Panao",
            "Pachitea / Chaglla",
            "Pachitea / Molino",
            "Pachitea / Umari",
            "Puerto Inca / Puerto Inca",
            "Puerto Inca / Codo Del Pozuzo",
            "Puerto Inca / Honoria",
            "Puerto Inca / Tournavista",
            "Puerto Inca / Yuyapichis",
            "Yarowilca / Chavinillo",
            "Yarowilca / Cahuac",
            "Yarowilca / Chacabamba",
            "Yarowilca / Aparicio Pomares",
            "Yarowilca / Jacas Chico",
            "Yarowilca / Obas",
            "Yarowilca / Pampamarca",
            "Yarowilca / Choras",
        ],

        "HUV" => [
            "Acobamba / Acobamba",
            "Acobamba / Andabamba",
            "Acobamba / Anta",
            "Acobamba / Caja",
            "Acobamba / Marcas",
            "Acobamba / Paucara",
            "Acobamba / Pomacocha",
            "Acobamba / Rosario",
            "Angaraes / Lircay",
            "Angaraes / Anchonga",
            "Angaraes / Callanmarca",
            "Angaraes / Ccochaccasa",
            "Angaraes / Chincho",
            "Angaraes / Congalla",
            "Angaraes / Huanca-Huanca",
            "Angaraes / Huayllay Grande",
            "Angaraes / Julcamarca",
            "Angaraes / San Antonio De Antaparco",
            "Angaraes / Santo Tomas De Pata",
            "Angaraes / Secclla",
            "Castrovirreyna / Castrovirreyna",
            "Castrovirreyna / Arma",
            "Castrovirreyna / Aurahua",
            "Castrovirreyna / Capillas",
            "Castrovirreyna / Chupamarca",
            "Castrovirreyna / Cocas",
            "Castrovirreyna / Huachos",
            "Castrovirreyna / Huamatambo",
            "Castrovirreyna / Mollepampa",
            "Castrovirreyna / San Juan",
            "Castrovirreyna / Santa Ana",
            "Castrovirreyna / Tantara",
            "Castrovirreyna / Ticrapo",
            "Churcampa / Churcampa",
            "Churcampa / Anco",
            "Churcampa / Chinchihuasi",
            "Churcampa / El Carmen",
            "Churcampa / La Merced",
            "Churcampa / Locroja",
            "Churcampa / Paucarbamba",
            "Churcampa / San Miguel De Mayocc",
            "Churcampa / San Pedro De Coris",
            "Churcampa / Pachamarca",
            "Churcampa / Cosme",
            "Huancavelica / Huancavelica",
            "Huancavelica / Acobambilla",
            "Huancavelica / Acoria",
            "Huancavelica / Conayca",
            "Huancavelica / Cuenca",
            "Huancavelica / Huachocolpa",
            "Huancavelica / Huayllahuara",
            "Huancavelica / Izcuchaca",
            "Huancavelica / Laria",
            "Huancavelica / Manta",
            "Huancavelica / Mariscal Caceres",
            "Huancavelica / Moya",
            "Huancavelica / Nuevo Occoro",
            "Huancavelica / Palca",
            "Huancavelica / Pilchaca",
            "Huancavelica / Vilca",
            "Huancavelica / Yauli",
            "Huancavelica / Ascension",
            "Huancavelica / Huando",
            "Huaytara / Huaytara",
            "Huaytara / Ayavi",
            "Huaytara / Cordova",
            "Huaytara / Huayacundo Arma",
            "Huaytara / Laramarca",
            "Huaytara / Ocoyo",
            "Huaytara / Pilpichaca",
            "Huaytara / Querco",
            "Huaytara / Quito-Arma",
            "Huaytara / San Antonio De Cusicancha",
            "Huaytara / San Francisco De Sangayaico",
            "Huaytara / San Isidro",
            "Huaytara / Santiago De Chocorvos",
            "Huaytara / Santiago De Quirahuara",
            "Huaytara / Santo Domingo De Capillas",
            "Huaytara / Tambo",
            "Tayacaja / Pampas",
            "Tayacaja / Acostambo",
            "Tayacaja / Acraquia",
            "Tayacaja / Ahuaycha",
            "Tayacaja / Colcabamba",
            "Tayacaja / Daniel Hernandez",
            "Tayacaja / Huachocolpa",
            "Tayacaja / Huaribamba",
            "Tayacaja / Ñahuimpuquio",
            "Tayacaja / Pazos",
            "Tayacaja / Quishuar",
            "Tayacaja / Salcabamba",
            "Tayacaja / Salcahuasi",
            "Tayacaja / San Marcos De Rocchac",
            "Tayacaja / Surcubamba",
            "Tayacaja / Tintay Puncu",
            "Tayacaja / Quichuas",
            "Tayacaja / Andaymarca",
            "Tayacaja / Roble",
            "Tayacaja / Pichos",
            "Tayacaja / Santiago De Tucuma",
            "Tayacaja / Lambras",
            "Tayacaja / Cochabamba",
        ],

        "ICA" => [
            "Chincha / Chincha Alta",
            "Chincha / Alto Laran",
            "Chincha / Chavin",
            "Chincha / Chincha Baja",
            "Chincha / El Carmen",
            "Chincha / Grocio Prado",
            "Chincha / Pueblo Nuevo",
            "Chincha / San Juan De Yanac",
            "Chincha / San Pedro De Huacarpana",
            "Chincha / Sunampe",
            "Chincha / Tambo De Mora",
            "Ica / Ica",
            "Ica / La Tinguiña",
            "Ica / Los Aquijes",
            "Ica / Ocucaje",
            "Ica / Pachacutec",
            "Ica / Parcona",
            "Ica / Pueblo Nuevo",
            "Ica / Salas",
            "Ica / San Jose De Los Molinos",
            "Ica / San Juan Bautista",
            "Ica / Santiago",
            "Ica / Subtanjalla",
            "Ica / Tate",
            "Ica / Yauca Del Rosario",
            "Nazca / Nazca",
            "Nazca / Changuillo",
            "Nazca / El Ingenio",
            "Nazca / Marcona",
            "Nazca / Vista Alegre",
            "Palpa / Palpa",
            "Palpa / Llipata",
            "Palpa / Rio Grande",
            "Palpa / Santa Cruz",
            "Palpa / Tibillo",
            "Pisco / Pisco",
            "Pisco / Huancano",
            "Pisco / Humay",
            "Pisco / Independencia",
            "Pisco / Paracas",
            "Pisco / San Andres",
            "Pisco / San Clemente",
            "Pisco / Tupac Amaru Inca",
        ],

        "JUN" => [
            "Chanchamayo / Chanchamayo",
            "Chanchamayo / Perene",
            "Chanchamayo / Pichanaqui",
            "Chanchamayo / San Luis De Shuaro",
            "Chanchamayo / San Ramon",
            "Chanchamayo / Vitoc",
            "Chupaca / Chupaca",
            "Chupaca / Ahuac",
            "Chupaca / Chongos Bajo",
            "Chupaca / Huachac",
            "Chupaca / Huamancaca Chico",
            "Chupaca / San Juan De Yscos",
            "Chupaca / San Juan De Jarpa",
            "Chupaca / Tres De Diciembre",
            "Chupaca / Yanacancha",
            "Concepcion / Concepcion",
            "Concepcion / Aco",
            "Concepcion / Andamarca",
            "Concepcion / Chambara",
            "Concepcion / Cochas",
            "Concepcion / Comas",
            "Concepcion / Heroinas Toledo",
            "Concepcion / Manzanares",
            "Concepcion / Mariscal Castilla",
            "Concepcion / Matahuasi",
            "Concepcion / Mito",
            "Concepcion / Nueve De Julio",
            "Concepcion / Orcotuna",
            "Concepcion / San Jose De Quero",
            "Concepcion / Santa Rosa De Ocopa",
            "Huancayo / Huancayo",
            "Huancayo / Carhuacallanga",
            "Huancayo / Chacapampa",
            "Huancayo / Chicche",
            "Huancayo / Chilca",
            "Huancayo / Chongos Alto",
            "Huancayo / Chupuro",
            "Huancayo / Colca",
            "Huancayo / Cullhuas",
            "Huancayo / El Tambo",
            "Huancayo / Huacrapuquio",
            "Huancayo / Hualhuas",
            "Huancayo / Huancan",
            "Huancayo / Huasicancha",
            "Huancayo / Huayucachi",
            "Huancayo / Ingenio",
            "Huancayo / Pariahuanca",
            "Huancayo / Pilcomayo",
            "Huancayo / Pucara",
            "Huancayo / Quichuay",
            "Huancayo / Quilcas",
            "Huancayo / San Agustin",
            "Huancayo / San Jeronimo De Tunan",
            "Huancayo / Saño",
            "Huancayo / Sapallanga",
            "Huancayo / Sicaya",
            "Huancayo / Santo Domingo De Acobamba",
            "Huancayo / Viques",
            "Jauja / Jauja",
            "Jauja / Acolla",
            "Jauja / Apata",
            "Jauja / Ataura",
            "Jauja / Canchayllo",
            "Jauja / Curicaca",
            "Jauja / El Mantaro",
            "Jauja / Huamali",
            "Jauja / Huaripampa",
            "Jauja / Huertas",
            "Jauja / Janjaillo",
            "Jauja / Julcan",
            "Jauja / Leonor Ordoñez",
            "Jauja / Llocllapampa",
            "Jauja / Marco",
            "Jauja / Masma",
            "Jauja / Masma Chicche",
            "Jauja / Molinos",
            "Jauja / Monobamba",
            "Jauja / Muqui",
            "Jauja / Muquiyauyo",
            "Jauja / Paca",
            "Jauja / Paccha",
            "Jauja / Pancan",
            "Jauja / Parco",
            "Jauja / Pomacancha",
            "Jauja / Ricran",
            "Jauja / San Lorenzo",
            "Jauja / San Pedro De Chunan",
            "Jauja / Sausa",
            "Jauja / Sincos",
            "Jauja / Tunan Marca",
            "Jauja / Yauli",
            "Jauja / Yauyos",
            "Junin / Junin",
            "Junin / Carhuamayo",
            "Junin / Ondores",
            "Junin / Ulcumayo",
            "Satipo / Satipo",
            "Satipo / Coviriali",
            "Satipo / Llaylla",
            "Satipo / Mazamari",
            "Satipo / Pampa Hermosa",
            "Satipo / Pangoa",
            "Satipo / Rio Negro",
            "Satipo / Rio Tambo",
            "Satipo / Vizcatan Del Ene",
            "Tarma / Tarma",
            "Tarma / Acobamba",
            "Tarma / Huaricolca",
            "Tarma / Huasahuasi",
            "Tarma / La Union",
            "Tarma / Palca",
            "Tarma / Palcamayo",
            "Tarma / San Pedro De Cajas",
            "Tarma / Tapo",
            "Yauli / La Oroya",
            "Yauli / Chacapalpa",
            "Yauli / Huay-Huay",
            "Yauli / Marcapomacocha",
            "Yauli / Morococha",
            "Yauli / Paccha",
            "Yauli / Santa Barbara De Carhuacayan",
            "Yauli / Santa Rosa De Sacco",
            "Yauli / Suitucancha",
            "Yauli / Yauli",
        ],

        "LAL" => [
            "Ascope / Ascope",
            "Ascope / Chicama",
            "Ascope / Chocope",
            "Ascope / Magdalena De Cao",
            "Ascope / Paijan",
            "Ascope / Razuri",
            "Ascope / Santiago De Cao",
            "Ascope / Casa Grande",
            "Bolivar / Bolivar",
            "Bolivar / Bambamarca",
            "Bolivar / Condormarca",
            "Bolivar / Longotea",
            "Bolivar / Uchumarca",
            "Bolivar / Ucuncha",
            "Chepen / Chepen",
            "Chepen / Pacanga",
            "Chepen / Pueblo Nuevo",
            "Gran Chimu / Cascas",
            "Gran Chimu / Lucma",
            "Gran Chimu / Marmot",
            "Gran Chimu / Sayapullo",
            "Julcan / Julcan",
            "Julcan / Calamarca",
            "Julcan / Carabamba",
            "Julcan / Huaso",
            "Otuzco / Otuzco",
            "Otuzco / Agallpampa",
            "Otuzco / Charat",
            "Otuzco / Huaranchal",
            "Otuzco / La Cuesta",
            "Otuzco / Mache",
            "Otuzco / Paranday",
            "Otuzco / Salpo",
            "Otuzco / Sinsicap",
            "Otuzco / Usquil",
            "Pacasmayo / San Pedro De Lloc",
            "Pacasmayo / Guadalupe",
            "Pacasmayo / Jequetepeque",
            "Pacasmayo / Pacasmayo",
            "Pacasmayo / San Jose",
            "Pataz / Tayabamba",
            "Pataz / Buldibuyo",
            "Pataz / Chillia",
            "Pataz / Huancaspata",
            "Pataz / Huaylillas",
            "Pataz / Huayo",
            "Pataz / Ongon",
            "Pataz / Parcoy",
            "Pataz / Pataz",
            "Pataz / Pias",
            "Pataz / Santiago De Challas",
            "Pataz / Taurija",
            "Pataz / Urpay",
            "Sanchez Carrion / Huamachuco",
            "Sanchez Carrion / Chugay",
            "Sanchez Carrion / Cochorco",
            "Sanchez Carrion / Curgos",
            "Sanchez Carrion / Marcabal",
            "Sanchez Carrion / Sanagoran",
            "Sanchez Carrion / Sarin",
            "Sanchez Carrion / Sartimbamba",
            "Santiago De Chuco / Santiago De Chuco",
            "Santiago De Chuco / Angasmarca",
            "Santiago De Chuco / Cachicadan",
            "Santiago De Chuco / Mollebamba",
            "Santiago De Chuco / Mollepata",
            "Santiago De Chuco / Quiruvilca",
            "Santiago De Chuco / Santa Cruz De Chuca",
            "Santiago De Chuco / Sitabamba",
            "Trujillo / Trujillo",
            "Trujillo / El Porvenir",
            "Trujillo / Florencia De Mora",
            "Trujillo / Huanchaco",
            "Trujillo / La Esperanza",
            "Trujillo / Laredo",
            "Trujillo / Moche",
            "Trujillo / Poroto",
            "Trujillo / Salaverry",
            "Trujillo / Simbal",
            "Trujillo / Victor Larco Herrera",
            "Viru / Viru",
            "Viru / Chao",
            "Viru / Guadalupito",
        ],

        "LAM" => [
            "Chiclayo / Chiclayo",
            "Chiclayo / Chongoyape",
            "Chiclayo / Eten",
            "Chiclayo / Eten Puerto",
            "Chiclayo / Jose Leonardo Ortiz",
            "Chiclayo / La Victoria",
            "Chiclayo / Lagunas",
            "Chiclayo / Monsefu",
            "Chiclayo / Nueva Arica",
            "Chiclayo / Oyotun",
            "Chiclayo / Picsi",
            "Chiclayo / Pimentel",
            "Chiclayo / Reque",
            "Chiclayo / Santa Rosa",
            "Chiclayo / Saña",
            "Chiclayo / Cayalti",
            "Chiclayo / Patapo",
            "Chiclayo / Pomalca",
            "Chiclayo / Pucala",
            "Chiclayo / Tuman",
            "Ferreñafe / Ferreñafe",
            "Ferreñafe / Cañaris",
            "Ferreñafe / Incahuasi",
            "Ferreñafe / Manuel Antonio Mesones Muro",
            "Ferreñafe / Pitipo",
            "Ferreñafe / Pueblo Nuevo",
            "Lambayeque / Lambayeque",
            "Lambayeque / Chochope",
            "Lambayeque / Illimo",
            "Lambayeque / Jayanca",
            "Lambayeque / Mochumi",
            "Lambayeque / Morrope",
            "Lambayeque / Motupe",
            "Lambayeque / Olmos",
            "Lambayeque / Pacora",
            "Lambayeque / Salas",
            "Lambayeque / San Jose",
            "Lambayeque / Tucume",
        ],

        "LIM" => [
            "Barranca / Barranca",
            "Barranca / Paramonga",
            "Barranca / Pativilca",
            "Barranca / Supe",
            "Barranca / Supe Puerto",
            "Cajatambo / Cajatambo",
            "Cajatambo / Copa",
            "Cajatambo / Gorgor",
            "Cajatambo / Huancapon",
            "Cajatambo / Manas",
            "Canta / Canta",
            "Canta / Arahuay",
            "Canta / Huamantanga",
            "Canta / Huaros",
            "Canta / Lachaqui",
            "Canta / San Buenaventura",
            "Canta / Santa Rosa De Quives",
            "Cañete / San Vicente De Cañete",
            "Cañete / Asia",
            "Cañete / Calango",
            "Cañete / Cerro Azul",
            "Cañete / Chilca",
            "Cañete / Coayllo",
            "Cañete / Imperial",
            "Cañete / Lunahuana",
            "Cañete / Mala",
            "Cañete / Nuevo Imperial",
            "Cañete / Pacaran",
            "Cañete / Quilmana",
            "Cañete / San Antonio",
            "Cañete / San Luis",
            "Cañete / Santa Cruz De Flores",
            "Cañete / Zuñiga",
            "Huaral / Huaral",
            "Huaral / Atavillos Alto",
            "Huaral / Atavillos Bajo",
            "Huaral / Aucallama",
            "Huaral / Chancay",
            "Huaral / Ihuari",
            "Huaral / Lampian",
            "Huaral / Pacaraos",
            "Huaral / San Miguel De Acos",
            "Huaral / Santa Cruz De Andamarca",
            "Huaral / Sumbilca",
            "Huaral / Veintisiete De Noviembre",
            "Huarochiri / Matucana",
            "Huarochiri / Antioquia",
            "Huarochiri / Callahuanca",
            "Huarochiri / Carampoma",
            "Huarochiri / Chicla",
            "Huarochiri / Cuenca",
            "Huarochiri / Huachupampa",
            "Huarochiri / Huanza",
            "Huarochiri / Huarochiri",
            "Huarochiri / Lahuaytambo",
            "Huarochiri / Langa",
            "Huarochiri / Laraos",
            "Huarochiri / Mariatana",
            "Huarochiri / Ricardo Palma",
            "Huarochiri / San Andres De Tupicocha",
            "Huarochiri / San Antonio",
            "Huarochiri / San Bartolome",
            "Huarochiri / San Damian",
            "Huarochiri / San Juan De Iris",
            "Huarochiri / San Juan De Tantaranche",
            "Huarochiri / San Lorenzo De Quinti",
            "Huarochiri / San Mateo",
            "Huarochiri / San Mateo De Otao",
            "Huarochiri / San Pedro De Casta",
            "Huarochiri / San Pedro De Huancayre",
            "Huarochiri / Sangallaya",
            "Huarochiri / Santa Cruz De Cocachacra",
            "Huarochiri / Santa Eulalia",
            "Huarochiri / Santiago De Anchucaya",
            "Huarochiri / Santiago De Tuna",
            "Huarochiri / Santo Domingo De Los Olleros",
            "Huarochiri / Surco",
            "Huaura / Huacho",
            "Huaura / Ambar",
            "Huaura / Caleta De Carquin",
            "Huaura / Checras",
            "Huaura / Hualmay",
            "Huaura / Huaura",
            "Huaura / Leoncio Prado",
            "Huaura / Paccho",
            "Huaura / Santa Leonor",
            "Huaura / Santa Maria",
            "Huaura / Sayan",
            "Huaura / Vegueta",
            "Oyon / Oyon",
            "Oyon / Andajes",
            "Oyon / Caujul",
            "Oyon / Cochamarca",
            "Oyon / Navan",
            "Oyon / Pachangara",
            "Yauyos / Yauyos",
            "Yauyos / Alis",
            "Yauyos / Ayauca",
            "Yauyos / Ayaviri",
            "Yauyos / Azangaro",
            "Yauyos / Cacra",
            "Yauyos / Carania",
            "Yauyos / Catahuasi",
            "Yauyos / Chocos",
            "Yauyos / Cochas",
            "Yauyos / Colonia",
            "Yauyos / Hongos",
            "Yauyos / Huampara",
            "Yauyos / Huancaya",
            "Yauyos / Huangascar",
            "Yauyos / Huantan",
            "Yauyos / Huañec",
            "Yauyos / Laraos",
            "Yauyos / Lincha",
            "Yauyos / Madean",
            "Yauyos / Miraflores",
            "Yauyos / Omas",
            "Yauyos / Putinza",
            "Yauyos / Quinches",
            "Yauyos / Quinocay",
            "Yauyos / San Joaquin",
            "Yauyos / San Pedro De Pilas",
            "Yauyos / Tanta",
            "Yauyos / Tauripampa",
            "Yauyos / Tomas",
            "Yauyos / Tupe",
            "Yauyos / Viñac",
            "Yauyos / Vitis",
        ],

        "LMA" => [
            "Lima",
            "Ancon",
            "Ate",
            "Barranco",
            "Breña",
            "Carabayllo",
            "Chaclacayo",
            "Chorrillos",
            "Cieneguilla",
            "Comas",
            "El Agustino",
            "Independencia",
            "Jesus Maria",
            "La Molina",
            "La Victoria",
            "Lince",
            "Los Olivos",
            "Lurigancho",
            "Lurin",
            "Magdalena Del Mar",
            "Pueblo Libre",
            "Miraflores",
            "Pachacamac",
            "Pucusana",
            "Puente Piedra",
            "Punta Hermosa",
            "Punta Negra",
            "Rimac",
            "San Bartolo",
            "San Borja",
            "San Isidro",
            "San Juan De Lurigancho",
            "San Juan De Miraflores",
            "San Luis",
            "San Martin De Porres",
            "San Miguel",
            "Santa Anita",
            "Santa Maria Del Mar",
            "Santa Rosa",
            "Santiago De Surco",
            "Surquillo",
            "Villa El Salvador",
            "Villa Maria Del Triunfo",
            "Santa Maria De Huachipa",
        ],

        "LOR" => [
            "Alto Amazonas / Yurimaguas",
            "Alto Amazonas / Balsapuerto",
            "Alto Amazonas / Jeberos",
            "Alto Amazonas / Lagunas",
            "Alto Amazonas / Santa Cruz",
            "Alto Amazonas / Teniente Cesar Lopez Rojas",
            "Datem Del Marañon / Barranca",
            "Datem Del Marañon / Cahuapanas",
            "Datem Del Marañon / Manseriche",
            "Datem Del Marañon / Morona",
            "Datem Del Marañon / Pastaza",
            "Datem Del Marañon / Andoas",
            "Loreto / Nauta",
            "Loreto / Parinari",
            "Loreto / Tigre",
            "Loreto / Trompeteros",
            "Loreto / Urarinas",
            "Mariscal Ramon Castilla / Ramon Castilla",
            "Mariscal Ramon Castilla / Pebas",
            "Mariscal Ramon Castilla / Yavari",
            "Mariscal Ramon Castilla / San Pablo",
            "Maynas / Iquitos",
            "Maynas / Alto Nanay",
            "Maynas / Fernando Lores",
            "Maynas / Indiana",
            "Maynas / Las Amazonas",
            "Maynas / Mazan",
            "Maynas / Napo",
            "Maynas / Punchana",
            "Maynas / Torres Causana",
            "Maynas / Belen",
            "Maynas / San Juan Bautista",
            "Maynas / Putumayo",
            "Maynas / Teniente Manuel Clavero",
            "Putumayo / Putumayo",
            "Putumayo / Rosa Panduro",
            "Putumayo / Teniente Manuel Clavero",
            "Putumayo / Yaguas",
            "Requena / Requena",
            "Requena / Alto Tapiche",
            "Requena / Capelo",
            "Requena / Emilio San Martin",
            "Requena / Maquia",
            "Requena / Puinahua",
            "Requena / Saquena",
            "Requena / Soplin",
            "Requena / Tapiche",
            "Requena / Jenaro Herrera",
            "Requena / Yaquerana",
            "Ucayali / Contamana",
            "Ucayali / Inahuaya",
            "Ucayali / Padre Marquez",
            "Ucayali / Pampa Hermosa",
            "Ucayali / Sarayacu",
            "Ucayali / Vargas Guerra",
        ],

        "MDD" => [
            "Manu / Manu",
            "Manu / Fitzcarrald",
            "Manu / Madre De Dios",
            "Manu / Huepetuhe",
            "Tahuamanu / Iñapari",
            "Tahuamanu / Iberia",
            "Tahuamanu / Tahuamanu",
            "Tambopata / Tambopata",
            "Tambopata / Inambari",
            "Tambopata / Las Piedras",
            "Tambopata / Laberinto",
        ],

        "MOQ" => [
            "General Sanchez Cerro / Omate",
            "General Sanchez Cerro / Chojata",
            "General Sanchez Cerro / Coalaque",
            "General Sanchez Cerro / Ichuña",
            "General Sanchez Cerro / La Capilla",
            "General Sanchez Cerro / Lloque",
            "General Sanchez Cerro / Matalaque",
            "General Sanchez Cerro / Puquina",
            "General Sanchez Cerro / Quinistaquillas",
            "General Sanchez Cerro / Ubinas",
            "General Sanchez Cerro / Yunga",
            "Ilo / Ilo",
            "Ilo / El Algarrobal",
            "Ilo / Pacocha",
            "Mariscal Nieto / San Antonio",
            "Mariscal Nieto / Moquegua",
            "Mariscal Nieto / Carumas",
            "Mariscal Nieto / Cuchumbaya",
            "Mariscal Nieto / Samegua",
            "Mariscal Nieto / San Cristobal",
            "Mariscal Nieto / Torata",
        ],

        "PAS" => [
            "Daniel Alcides Carrion / Yanahuanca",
            "Daniel Alcides Carrion / Chacayan",
            "Daniel Alcides Carrion / Goyllarisquizga",
            "Daniel Alcides Carrion / Paucar",
            "Daniel Alcides Carrion / San Pedro De Pillao",
            "Daniel Alcides Carrion / Santa Ana De Tusi",
            "Daniel Alcides Carrion / Tapuc",
            "Daniel Alcides Carrion / Vilcabamba",
            "Oxapampa / Oxapampa",
            "Oxapampa / Chontabamba",
            "Oxapampa / Huancabamba",
            "Oxapampa / Palcazu",
            "Oxapampa / Pozuzo",
            "Oxapampa / Puerto Bermudez",
            "Oxapampa / Villa Rica",
            "Oxapampa / Constitucion",
            "Pasco / Chaupimarca",
            "Pasco / Huachon",
            "Pasco / Huariaca",
            "Pasco / Huayllay",
            "Pasco / Ninacaca",
            "Pasco / Pallanchacra",
            "Pasco / Paucartambo",
            "Pasco / San Francisco De Asis De Yarusyacan",
            "Pasco / Simon Bolivar",
            "Pasco / Ticlacayan",
            "Pasco / Tinyahuarco",
            "Pasco / Vicco",
            "Pasco / Yanacancha",
        ],

        "PIU" => [
            "Ayabaca / Ayabaca",
            "Ayabaca / Frias",
            "Ayabaca / Jilili",
            "Ayabaca / Lagunas",
            "Ayabaca / Montero",
            "Ayabaca / Pacaipampa",
            "Ayabaca / Paimas",
            "Ayabaca / Sapillica",
            "Ayabaca / Sicchez",
            "Ayabaca / Suyo",
            "Huancabamba / Huancabamba",
            "Huancabamba / Canchaque",
            "Huancabamba / El Carmen De La Frontera",
            "Huancabamba / Huarmaca",
            "Huancabamba / Lalaquiz",
            "Huancabamba / San Miguel De El Faique",
            "Huancabamba / Sondor",
            "Huancabamba / Sondorillo",
            "Morropon / Chulucanas",
            "Morropon / Buenos Aires",
            "Morropon / Chalaco",
            "Morropon / La Matanza",
            "Morropon / Morropon",
            "Morropon / Salitral",
            "Morropon / San Juan De Bigote",
            "Morropon / Santa Catalina De Mossa",
            "Morropon / Santo Domingo",
            "Morropon / Yamango",
            "Paita / Paita",
            "Paita / Amotape",
            "Paita / Arenal",
            "Paita / Colan",
            "Paita / La Huaca",
            "Paita / Tamarindo",
            "Paita / Vichayal",
            "Piura / Piura",
            "Piura / Castilla",
            "Piura / Catacaos",
            "Piura / Cura Mori",
            "Piura / El Tallan",
            "Piura / La Arena",
            "Piura / La Union",
            "Piura / Las Lomas",
            "Piura / Tambo Grande",
            "Piura / Veintiseis De Octubre",
            "Sechura / Sechura",
            "Sechura / Bellavista De La Union",
            "Sechura / Bernal",
            "Sechura / Cristo Nos Valga",
            "Sechura / Vice",
            "Sechura / Rinconada Llicuar",
            "Sullana / Sullana",
            "Sullana / Bellavista",
            "Sullana / Ignacio Escudero",
            "Sullana / Lancones",
            "Sullana / Marcavelica",
            "Sullana / Miguel Checa",
            "Sullana / Querecotillo",
            "Sullana / Salitral",
            "Talara / Pariñas",
            "Talara / El Alto",
            "Talara / La Brea",
            "Talara / Lobitos",
            "Talara / Los Organos",
            "Talara / Mancora",
        ],

        "PUN" => [
            "Azangaro / Azangaro",
            "Azangaro / Achaya",
            "Azangaro / Arapa",
            "Azangaro / Asillo",
            "Azangaro / Caminaca",
            "Azangaro / Chupa",
            "Azangaro / Jose Domingo Choquehuanca",
            "Azangaro / Muñani",
            "Azangaro / Potoni",
            "Azangaro / Saman",
            "Azangaro / San Anton",
            "Azangaro / San Jose",
            "Azangaro / San Juan De Salinas",
            "Azangaro / Santiago De Pupuja",
            "Azangaro / Tirapata",
            "Carabaya / Macusani",
            "Carabaya / Ajoyani",
            "Carabaya / Ayapata",
            "Carabaya / Coasa",
            "Carabaya / Corani",
            "Carabaya / Crucero",
            "Carabaya / Ituata",
            "Carabaya / Ollachea",
            "Carabaya / San Gaban",
            "Carabaya / Usicayos",
            "Chucuito / Juli",
            "Chucuito / Desaguadero",
            "Chucuito / Huacullani",
            "Chucuito / Kelluyo",
            "Chucuito / Pisacoma",
            "Chucuito / Pomata",
            "Chucuito / Zepita",
            "El Collao / Ilave",
            "El Collao / Capazo",
            "El Collao / Pilcuyo",
            "El Collao / Santa Rosa",
            "El Collao / Conduriri",
            "Huancane / Huancane",
            "Huancane / Cojata",
            "Huancane / Huatasani",
            "Huancane / Inchupalla",
            "Huancane / Pusi",
            "Huancane / Rosaspata",
            "Huancane / Taraco",
            "Huancane / Vilque Chico",
            "Lampa / Lampa",
            "Lampa / Cabanilla",
            "Lampa / Calapuja",
            "Lampa / Nicasio",
            "Lampa / Ocuviri",
            "Lampa / Palca",
            "Lampa / Paratia",
            "Lampa / Pucara",
            "Lampa / Santa Lucia",
            "Lampa / Vilavila",
            "Melgar / Ayaviri",
            "Melgar / Antauta",
            "Melgar / Cupi",
            "Melgar / Llalli",
            "Melgar / Macari",
            "Melgar / Nuñoa",
            "Melgar / Orurillo",
            "Melgar / Santa Rosa",
            "Melgar / Umachiri",
            "Moho / Moho",
            "Moho / Conima",
            "Moho / Huayrapata",
            "Moho / Tilali",
            "Puno / Puno",
            "Puno / Acora",
            "Puno / Amantani",
            "Puno / Atuncolla",
            "Puno / Capachica",
            "Puno / Chucuito",
            "Puno / Coata",
            "Puno / Huata",
            "Puno / Mañazo",
            "Puno / Paucarcolla",
            "Puno / Pichacani",
            "Puno / Plateria",
            "Puno / San Antonio",
            "Puno / Tiquillaca",
            "Puno / Vilque",
            "San Antonio De Putina / Putina",
            "San Antonio De Putina / Ananea",
            "San Antonio De Putina / Pedro Vilca Apaza",
            "San Antonio De Putina / Quilcapuncu",
            "San Antonio De Putina / Sina",
            "San Roman / Juliaca",
            "San Roman / Cabana",
            "San Roman / Cabanillas",
            "San Roman / Caracoto",
            "San Roman / San Miguel",
            "Sandia / Sandia",
            "Sandia / Cuyocuyo",
            "Sandia / Limbani",
            "Sandia / Patambuco",
            "Sandia / Phara",
            "Sandia / Quiaca",
            "Sandia / San Juan Del Oro",
            "Sandia / Yanahuaya",
            "Sandia / Alto Inambari",
            "Sandia / San Pedro De Putina Punco",
            "Yunguyo / Yunguyo",
            "Yunguyo / Anapia",
            "Yunguyo / Copani",
            "Yunguyo / Cuturapi",
            "Yunguyo / Ollaraya",
            "Yunguyo / Tinicachi",
            "Yunguyo / Unicachi",
        ],

        "SAM" => [
            "Bellavista / Bellavista",
            "Bellavista / Alto Biavo",
            "Bellavista / Bajo Biavo",
            "Bellavista / Huallaga",
            "Bellavista / San Pablo",
            "Bellavista / San Rafael",
            "El Dorado / San Jose De Sisa",
            "El Dorado / Agua Blanca",
            "El Dorado / San Martin",
            "El Dorado / Santa Rosa",
            "El Dorado / Shatoja",
            "Huallaga / Saposoa",
            "Huallaga / Alto Saposoa",
            "Huallaga / El Eslabon",
            "Huallaga / Piscoyacu",
            "Huallaga / Sacanche",
            "Huallaga / Tingo De Saposoa",
            "Lamas / Lamas",
            "Lamas / Alonso De Alvarado",
            "Lamas / Barranquita",
            "Lamas / Caynarachi",
            "Lamas / Cuñumbuqui",
            "Lamas / Pinto Recodo",
            "Lamas / Rumisapa",
            "Lamas / San Roque De Cumbaza",
            "Lamas / Shanao",
            "Lamas / Tabalosos",
            "Lamas / Zapatero",
            "Mariscal Caceres / Juanjui",
            "Mariscal Caceres / Campanilla",
            "Mariscal Caceres / Huicungo",
            "Mariscal Caceres / Pachiza",
            "Mariscal Caceres / Pajarillo",
            "Moyobamba / Moyobamba",
            "Moyobamba / Calzada",
            "Moyobamba / Habana",
            "Moyobamba / Jepelacio",
            "Moyobamba / Soritor",
            "Moyobamba / Yantalo",
            "Picota / Picota",
            "Picota / Buenos Aires",
            "Picota / Caspisapa",
            "Picota / Pilluana",
            "Picota / Pucacaca",
            "Picota / San Cristobal",
            "Picota / San Hilarion",
            "Picota / Shamboyacu",
            "Picota / Tingo De Ponasa",
            "Picota / Tres Unidos",
            "Rioja / Rioja",
            "Rioja / Awajun",
            "Rioja / Elias Soplin Vargas",
            "Rioja / Nueva Cajamarca",
            "Rioja / Pardo Miguel",
            "Rioja / Posic",
            "Rioja / San Fernando",
            "Rioja / Yorongos",
            "Rioja / Yuracyacu",
            "San Martin / Tarapoto",
            "San Martin / Alberto Leveau",
            "San Martin / Cacatachi",
            "San Martin / Chazuta",
            "San Martin / Chipurana",
            "San Martin / El Porvenir",
            "San Martin / Huimbayoc",
            "San Martin / Juan Guerra",
            "San Martin / La Banda De Shilcayo",
            "San Martin / Morales",
            "San Martin / Papaplaya",
            "San Martin / San Antonio",
            "San Martin / Sauce",
            "San Martin / Shapaja",
            "Tocache / Santa Lucia",
            "Tocache / Tocache",
            "Tocache / Nuevo Progreso",
            "Tocache / Polvora",
            "Tocache / Shunte",
            "Tocache / Uchiza",
        ],

        "TAC" => [
            "Candarave / Candarave",
            "Candarave / Cairani",
            "Candarave / Camilaca",
            "Candarave / Curibaya",
            "Candarave / Huanuara",
            "Candarave / Quilahuani",
            "Jorge Basadre / Locumba",
            "Jorge Basadre / Ilabaya",
            "Jorge Basadre / Ite",
            "Tacna / Tacna",
            "Tacna / Alto De La Alianza",
            "Tacna / Calana",
            "Tacna / Ciudad Nueva",
            "Tacna / Inclan",
            "Tacna / Pachia",
            "Tacna / Palca",
            "Tacna / Pocollay",
            "Tacna / Sama",
            "Tacna / Coronel Gregorio Albarracin Lanchip",
            "Tacna / La Yarada Los Palos",
            "Tarata / Tarata",
            "Tarata / Chucatamani",
            "Tarata / Estique",
            "Tarata / Estique-Pampa",
            "Tarata / Sitajara",
            "Tarata / Susapaya",
            "Tarata / Tarucachi",
            "Tarata / Ticaco",
        ],

        "TUM" => [
            "Contralmirante Villar / Zorritos",
            "Contralmirante Villar / Casitas",
            "Contralmirante Villar / Canoas De Punta Sal",
            "Tumbes / Tumbes",
            "Tumbes / Corrales",
            "Tumbes / La Cruz",
            "Tumbes / Pampas De Hospital",
            "Tumbes / San Jacinto",
            "Tumbes / San Juan De La Virgen",
            "Zarumilla / Zarumilla",
            "Zarumilla / Aguas Verdes",
            "Zarumilla / Matapalo",
            "Zarumilla / Papayal",
        ],

        "UCA" => [
            "Atalaya / Raymondi",
            "Atalaya / Sepahua",
            "Atalaya / Tahuania",
            "Atalaya / Yurua",
            "Coronel Portillo / Calleria",
            "Coronel Portillo / Campoverde",
            "Coronel Portillo / Iparia",
            "Coronel Portillo / Masisea",
            "Coronel Portillo / Yarinacocha",
            "Coronel Portillo / Nueva Requena",
            "Coronel Portillo / Manantay",
            "Padre Abad / Padre Abad",
            "Padre Abad / Irazola",
            "Padre Abad / Curimana",
            "Padre Abad / Neshuya",
            "Padre Abad / Alexander Von Humboldt",
            "Padre Abad / Huipoca",
            "Padre Abad / Boqueron",
            "Purus / Purus",
        ],
    ];
    return $cities;
}
